[package]
name = "ratatui_json"
version = "0.0.1"
authors = ["kawarimidoll"]
license = "MIT"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
